name: 🔑 Access Request
description: Request permissions, credentials, or account access
title: "[Access] "
labels: ["status: new", "category: access"]
assignees:
  - Tim-Pook

body:
  - type: markdown
    attributes:
      value: |
        ## Access Request
        Request access to systems, servers, data, or services.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this request?
      options:
        - Low (can wait a week)
        - Medium (needed within a few days)
        - High (blocking my work)
        - Urgent (critical issue)
    validations:
      required: true

  - type: input
    id: resource
    attributes:
      label: What do you need access to?
      description: System, server, folder, or service name
      placeholder: "lab-server-1, shared drive, VPN"
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Why do you need this access?
      description: Brief justification
      placeholder: "Need to run experiments for my research project."
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Details (optional)
      description: Any other relevant information
      placeholder: "Permissions needed, duration, supervisor approval, etc."
    validations:
      required: false
