name: ⚡ Computing Resources
description: Issues with HPC, servers, or computing cluster resources
title: "[Compute] "
labels: ["status: new", "category: compute"]
assignees:
  - Tim-Pook

body:
  - type: markdown
    attributes:
      value: |
        ## Computing Resources Support
        Issues with HPC systems, servers, or computing clusters.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this issue?
      options:
        - Low (can wait a week)
        - Medium (needed within a few days)
        - High (blocking my work)
        - Urgent (critical issue)
    validations:
      required: true

  - type: input
    id: system
    attributes:
      label: System/Cluster
      description: Which computing system?
      placeholder: "lab-hpc-1, workstation-5"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What's the problem?
      description: Describe the issue
      placeholder: "Job won't submit, getting error 'Queue not found'."
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Details (optional)
      description: Any other relevant information
      placeholder: "Job ID, script, error messages, what you've tried, etc."
    validations:
      required: false
