name: 💾 Data/Storage Issue
description: Request help with data management, storage, or backup
title: "[Data] "
labels: ["status: new", "category: data"]
assignees:
  - Tim-Pook

body:
  - type: markdown
    attributes:
      value: |
        ## Data/Storage Request
        Need help with data storage, backup, or management.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this request?
      options:
        - Low (can wait a week)
        - Medium (needed within a few days)
        - High (blocking my work)
        - Urgent (data loss or critical issue)
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Storage Location
      description: Which storage system?
      placeholder: "Lab shared drive, server-1 /data folder"
    validations:
      required: true

  - type: textarea
    id: request
    attributes:
      label: What do you need?
      description: Describe your request
      placeholder: "Need 500GB more storage space for simulation data."
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Details (optional)
      description: Any other relevant information
      placeholder: "Data size, timeframe, backup requirements, etc."
    validations:
      required: false
