name: ❓ General Help
description: Questions or issues not covered by other categories
title: "[Help] "
labels: ["status: new", "category: other"]
assignees:
  - Tim-Pook

body:
  - type: markdown
    attributes:
      value: |
        ## General Help Request
        Have a question or need help? Fill in the essential details below.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this?
      options:
        - Low (can wait a week)
        - Medium (needed within a few days)
        - High (blocking my work)
        - Urgent (critical issue)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What do you need help with?
      description: Describe your question or request
      placeholder: "I need help understanding how to access the lab servers from home."
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Details (optional)
      description: Any other relevant information
      placeholder: "What I've tried, deadline, contact info, etc."
    validations:
      required: false
