name: 📋 Long-term Task
description: Non-urgent ongoing duties and projects for IT support
title: "[Long-term] "
labels: ["status: new", "category: long-term", "priority: low"]
assignees:
  - Tim-Pook

body:
  - type: markdown
    attributes:
      value: |
        ## Long-term Task Assignment
        For non-urgent, ongoing duties and projects over an extended period.

  - type: textarea
    id: task
    attributes:
      label: Task Description
      description: What needs to be accomplished?
      placeholder: "Setup new lab backup system with automated daily backups to NAS."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context & Requirements
      description: Background info and expected outcomes
      placeholder: "Need reliable backup solution. Current system is manual and error-prone. Should support 2TB data."
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Details (optional)
      description: Any other relevant information
      placeholder: "Timeline, resources needed, dependencies, etc."
    validations:
      required: false
