name: 🌐 Network Issue
description: Report connectivity or network problems
title: "[Network] "
labels: ["status: new", "category: network"]
assignees:
  - Tim-Pook

body:
  - type: markdown
    attributes:
      value: |
        ## Network Issue
        Having network connectivity problems? Let us know what's happening.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this issue?
      options:
        - Low (can wait a week)
        - Medium (needed within a few days)
        - High (blocking my work)
        - Urgent (critical issue)
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location/Device
      description: Where and what device?
      placeholder: "Lab 3 desktop, my laptop at home"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What's the problem?
      description: Describe the network issue
      placeholder: "Cannot connect to VPN, getting timeout errors."
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Details (optional)
      description: Any other relevant information
      placeholder: "Error messages, when it started, what you've tried, etc."
    validations:
      required: false
