name: 🛒 Procurement Request
description: Equipment, software, or service purchases
title: "[Procurement] "
labels: ["status: new", "category: procurement", "priority: low"]
assignees:
  - Tim-Pook

body:
  - type: markdown
    attributes:
      value: |
        ## Procurement Request
        Request for purchasing equipment, software, or services.

        **Note:** Procurement typically takes 4-8 weeks. Plan ahead!

  - type: textarea
    id: item
    attributes:
      label: What needs to be purchased?
      description: Item name, quantity, and specifications
      placeholder: "2x Dell Workstation with 64GB RAM, NVIDIA RTX 4090"
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Why is this needed?
      description: Brief justification for the purchase
      placeholder: "For deep learning model training. Current workstations are insufficient."
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Details (optional)
      description: Any other relevant information
      placeholder: "Budget, preferred vendor, timeline, grant number, etc."
    validations:
      required: false
