name: 💻 Software Support
description: Get help with software installation, configuration, or errors
title: "[Software] "
labels: ["status: new", "category: software"]
assignees:
  - Tim-Pook

body:
  - type: markdown
    attributes:
      value: |
        ## Software Support Request
        Need help with software? Tell us what you need.

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this issue?
      options:
        - Low (can wait a week)
        - Medium (needed within a few days)
        - High (blocking my work)
        - Urgent (critical issue)
    validations:
      required: true

  - type: input
    id: software
    attributes:
      label: Software
      description: What software and which system?
      placeholder: "Python 3.9 on workstation-5"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: What's the problem?
      description: Describe the issue or what you're trying to do
      placeholder: "Getting 'Module not found' error when importing pandas."
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Details (optional)
      description: Any other relevant information
      placeholder: "Error messages, what you've tried, screenshots, etc."
    validations:
      required: false
